"""Independent Banorte .pag golden authoring tool.

IMPORTANT: This module must NEVER import the production Banorte layout builder.
It duplicates the approved field tables from the design spec so the golden
fixture is not generated by the code under test.
"""

from __future__ import annotations

from pathlib import Path

# Locked positions from docs/superpowers/specs/... §9.4 (0-based, width 165).
LINE_WIDTH = 165
CRLF = b"\r\n"

# Synthetic payments (fictional only).
SYNTHETIC_PAYMENTS = (
    {"employee_number": "0000000011", "account_number": "1321431243", "amount_cents": 270000},
    {"employee_number": "0000000234", "account_number": "1326169484", "amount_cents": 230000},
    {"employee_number": "0000000548", "account_number": "1356107803", "amount_cents": 150050},
)

LAYOUT_DATE = "20260115"
CONSECUTIVE = "07"


def _pad_left(value: str, width: int, fill: str = "0") -> str:
    if len(value) > width:
        raise ValueError(f"value too wide for field: {len(value)}>{width}")
    return value.rjust(width, fill)


def _pad_right(value: str, width: int, fill: str = " ") -> str:
    if len(value) > width:
        raise ValueError(f"value too wide for field: {len(value)}>{width}")
    return value.ljust(width, fill)


def build_header_line(*, layout_date: str, consecutive: str, count: int, total_cents: int) -> str:
    parts = [
        "H",
        "NE",
        _pad_left("67059", 5),
        _pad_left(layout_date, 8),
        _pad_left(consecutive, 2),
        _pad_left(str(count), 6),
        _pad_left(str(total_cents), 15),
        "000000",
        "000000000000000",
        "000000",
        "000000000000000",
        "000000",
        "0",
        " " * 77,
    ]
    line = "".join(parts)
    if len(line) != LINE_WIDTH:
        raise ValueError(f"header length {len(line)}")
    return line


def build_detail_line(*, layout_date: str, employee_number: str, account_number: str, amount_cents: int) -> str:
    parts = [
        "D",
        _pad_left(layout_date, 8),
        _pad_left(employee_number, 10),
        " " * 40,
        " " * 40,
        _pad_left(str(amount_cents), 15),
        "072",
        "01",
        _pad_left(account_number, 18),
        "0",
        " ",
        "00000000",
        " " * 18,
    ]
    line = "".join(parts)
    if len(line) != LINE_WIDTH:
        raise ValueError(f"detail length {len(line)}")
    return line


def build_independent_pag(
    *,
    layout_date: str = LAYOUT_DATE,
    consecutive: str = CONSECUTIVE,
    payments: tuple[dict, ...] = SYNTHETIC_PAYMENTS,
) -> bytes:
    total = sum(int(p["amount_cents"]) for p in payments)
    lines = [
        build_header_line(
            layout_date=layout_date,
            consecutive=consecutive,
            count=len(payments),
            total_cents=total,
        )
    ]
    for p in payments:
        lines.append(
            build_detail_line(
                layout_date=layout_date,
                employee_number=str(p["employee_number"]),
                account_number=str(p["account_number"]),
                amount_cents=int(p["amount_cents"]),
            )
        )
    # CRLF between lines only; NO trailing CRLF.
    body = CRLF.join(line.encode("ascii") for line in lines)
    return body


def main() -> None:
    out = Path(__file__).with_name("synthetic_golden.pag")
    data = build_independent_pag()
    out.write_bytes(data)
    print(f"wrote {out} bytes={len(data)}")


if __name__ == "__main__":
    main()
