"""Contrato canónico de plantillas Excel Gestión IDSE / SUA."""

from __future__ import annotations

from pathlib import Path

TEMPLATES_DIR = Path(__file__).resolve().parent / "templates_excel"

COMPARATIVO_FILENAME = "Plantilla_Comparativo_Semanal_IDSE_SUA.xlsx"
MENSUAL_FILENAME = "Plantilla_Reporte_Mensual_IDSE_SUA.xlsx"

COMPARATIVO_SHA256 = "0ae398efc7c2dcadc171e4285c937a42fc3d13d143e3206ae61fe67d9466f98c"
MENSUAL_SHA256 = "3f72bb0ca58e9eef52ec899dd46327adcfa2d75200d0751279b6422e48e9d4c0"

COMPARATIVO_SHEETS = (
    "Resumen",
    "Detalle Comparativo",
    "Asistencia Semanal",
    "Movimientos Seleccionados",
    "Guía",
)

MENSUAL_SHEETS = (
    "Resumen",
    "Personal Mensual",
    "Asistencia Mensual",
    "Trayectoria Semanal",
    "Movimientos Seleccionados",
    "Pendientes",
    "Guía",
)

# Encabezados obligatorios por hoja (fila canónica de columnas).
COMPARATIVO_REQUIRED_HEADERS: dict[str, tuple[str, ...]] = {
    "Detalle Comparativo": (
        "ID registro",
        "Cliente",
        "Planta",
        "Periodo inicio",
        "Periodo fin",
        "Semana",
        "Núm. empleado",
        "Nombre en nómina",
        "Nombre en Headcount",
        "Método de match",
        "Estado del match",
        "Confianza %",
        "Puesto",
        "NSS",
        "RFC",
        "CURP",
        "SBC",
        "Resultado comparativo",
        "Semáforo",
        "Fecha sugerida",
        "Tipo movimiento final",
        "Enviar a bandeja",
        "Motivo / observaciones",
        "Revisado por",
        "Fecha revisión",
    ),
    "Asistencia Semanal": (
        "ID registro",
        "Cliente",
        "Planta",
        "Núm. empleado",
        "Nombre",
        "Puesto",
        "Estado match",
        "Día 1",
        "Día 2",
        "Día 3",
        "Día 4",
        "Día 5",
        "Día 6",
        "Día 7",
        "Total A",
        "Total F",
        "Total I/INC",
        "Total V",
        "Total D",
        "Primera A",
        "Última A",
    ),
    "Movimientos Seleccionados": (
        "Incluir",
        "Tipo movimiento",
        "RFC patronal",
        "Registro patronal",
        "Fecha movimiento",
        "NSS",
        "RFC trabajador",
        "CURP",
        "Apellido paterno",
        "Apellido materno",
        "Nombres",
        "SBC",
        "Cliente",
        "Planta",
        "Origen",
        "Motivo / observaciones",
        "Compatible IDSE",
        "Compatible SUA",
        "Estado de datos",
        "Motivo de exclusión",
    ),
    "Guía": (
        "Código",
        "Concepto",
        "Mantiene condición activa",
        "Cuenta como falta",
    ),
}

MENSUAL_REQUIRED_HEADERS: dict[str, tuple[str, ...]] = {
    "Personal Mensual": (
        "ID persona",
        "Núm. empleado",
        "Nombre en nómina",
        "Nombre en Headcount",
        "Método de match",
        "Estado match",
        "NSS",
        "RFC",
        "CURP",
        "SBC",
        "Cliente(s) del mes",
        "Planta(s) del mes",
        "Semanas incluidas",
        "Primera A",
        "Última A",
        "Total A",
        "Total F",
        "Total I/INC",
        "Total V",
        "Total D",
        "Estado mensual",
        "Posibles movimientos",
        "Movimientos confirmados",
        "Observaciones",
        "Revisado por",
        "Fecha revisión",
    ),
    "Asistencia Mensual": (
        "ID persona",
        "Núm. empleado",
        "Nombre",
        "Cliente",
        "Planta",
        "Estado mensual",
        "Primera A",
        "Última A",
        "Total A",
        "Total F",
        "Observaciones",
        "Día 1",
        "Día 2",
        "Día 3",
        "Día 4",
        "Día 5",
        "Día 6",
        "Día 7",
        "Día 8",
        "Día 9",
        "Día 10",
        "Día 11",
        "Día 12",
        "Día 13",
        "Día 14",
        "Día 15",
        "Día 16",
        "Día 17",
        "Día 18",
        "Día 19",
        "Día 20",
        "Día 21",
        "Día 22",
        "Día 23",
        "Día 24",
        "Día 25",
        "Día 26",
        "Día 27",
        "Día 28",
        "Día 29",
        "Día 30",
        "Día 31",
        "Total I/INC",
        "Total V",
        "Total D",
    ),
    "Trayectoria Semanal": (
        "ID persona",
        "Núm. empleado",
        "Nombre",
        "Cliente",
        "Planta",
        "Semana",
        "Periodo inicio",
        "Periodo fin",
        "Secuencia diaria",
        "Días A",
        "Faltas F",
        "I/INC",
        "Vacaciones V",
        "Descansos D",
        "Estado del tramo",
        "Evento sugerido",
        "Fecha sugerida",
        "Confirmación",
        "Observaciones",
    ),
    "Movimientos Seleccionados": (
        "Incluir",
        "Tipo movimiento",
        "RFC patronal",
        "Registro patronal",
        "Fecha movimiento",
        "NSS",
        "RFC trabajador",
        "CURP",
        "Apellido paterno",
        "Apellido materno",
        "Nombres",
        "SBC",
        "Cliente",
        "Planta",
        "Origen",
        "Motivo / observaciones",
        "Compatible IDSE",
        "Compatible SUA",
        "Estado de datos",
        "Motivo de exclusión",
    ),
    "Pendientes": (
        "Tipo pendiente",
        "ID persona",
        "Núm. empleado",
        "Nombre",
        "Cliente sugerido",
        "Planta",
        "Periodo / mes",
        "Detalle",
        "Sugerencia de la app",
        "Acción requerida",
        "Estado",
        "Responsable",
        "Fecha resolución",
    ),
    "Guía": (
        "Código",
        "Concepto",
        "Mantiene activo",
        "Rompe faltas consecutivas",
    ),
}

HEADER_ROW_BY_SHEET: dict[str, int] = {
    "Detalle Comparativo": 6,
    "Asistencia Semanal": 6,
    "Movimientos Seleccionados": 6,
    "Guía": 6,
    "Personal Mensual": 6,
    "Asistencia Mensual": 6,
    "Trayectoria Semanal": 6,
    "Pendientes": 6,
}


def comparativo_path() -> Path:
    return TEMPLATES_DIR / COMPARATIVO_FILENAME


def mensual_path() -> Path:
    return TEMPLATES_DIR / MENSUAL_FILENAME
